const languageData = {
    en: {
        // Navigation
        home: "Home",
        gameIntro: "Game Intro",
        media: "Media",
        guide: "Guide",
        talk: "Talk",
        
        // Game Intro Page
        gameTitle: "AppleShooter - Classic Shooting Game",
        gameDescription: "AppleShooter is a challenging shooting game where players must use a bow and arrow to precisely shoot apples placed on people's heads. The game tests players' accuracy, patience, and skill, with each shot potentially bringing victory or defeat.",
        gameplay: "Gameplay",
        basicControls: "Basic Controls",
        basicControlsDesc: "Use the mouse to aim: Move the mouse to adjust the direction of the arrow",
        chargeControl: "Hold left mouse button: Charge, arrow power increases with hold time",
        fireControl: "Release left mouse button: Fire the arrow",
        gameObjectives: "Game Objectives",
        gameObjectivesDesc: "Accurately hit the apple, avoid hitting the person",
        levelDifficulty: "Each level has different difficulties and challenges",
        highScore: "Get high scores through precise shooting",
        gameFeatures: "Game Features",
        gameFeaturesDesc: "Physics engine: Realistic arrow flight trajectory",
        increasingDifficulty: "Increasing difficulty: Gradually increasing game difficulty",
        instantFeedback: "Instant feedback: Intuitive hit effects",
        gameHistory: "Game History",
        gameHistoryDesc: "The inspiration for AppleShooter comes from the Swiss folk legend of William Tell.",
        developmentTeam: "Development Team",
        developmentTeamDesc: "AppleShooter is created by a passionate game development team.",
        developmentHistory: "Development History",
        history2005: "2005: Game concept born, early development started",
        history2006: "2006: First Flash version released",
        history2010: "2010: Improved version launched with new game mechanics",
        history2015: "2015: HTML5 version released, supporting mobile devices",
        history2020: "2020: Major upgrade, optimizing game experience",
        coreTeam: "Core Team",
        gameDesign: "Game Design:",
        gameDesigner: "John Smith - Senior game designer with 10 years of casual game development experience",
        programming: "Programming:",
        programmer: "Sarah Johnson - Lead programmer, focusing on physics engine optimization",
        artDesign: "Art Design:",
        artist: "Michael Chen - Senior game artist, responsible for visual style design",
        soundDesign: "Sound Design:",
        soundDesigner: "Lisa Wang - Sound designer, creating game music and sound effects",
        
        // Media Page
        gameMedia: "Game Media",
        gameScreenshots: "Game Screenshots",
        gameScreenshotsDesc: "View amazing in-game moments",
        gameMusic: "Game Music",
        gameMusicDesc: "Listen to the game soundtrack",
        gameVideos: "Game Videos",
        gameVideosDesc: "Watch gameplay videos",
        
        // Guide Page
        basicControlsGuide: "Basic Controls Guide",
        aimingSystem: "Aiming System",
        aimingSystemDesc: "Use mouse movement to adjust bow aim direction",
        shootingMechanism: "Shooting Mechanism",
        shootingMechanismDesc: "Hold left mouse button to charge",
        specialTechniques: "Special Techniques",
        specialTechniquesDesc: "Quick Click: Fast clicks for rapid shots",
        levelGuide: "Level Guide",
        beginnerLevels: "Beginner Levels (1-5)",
        beginnerLevelsDesc: "Stationary targets, close range",
        intermediateLevels: "Intermediate Levels (6-10)",
        intermediateLevelsDesc: "Slowly moving targets",
        advancedLevels: "Advanced Levels (11-15)",
        advancedLevelsDesc: "Fast moving targets",
        ultimateLevels: "Ultimate Levels (16-20)",
        ultimateLevelsDesc: "Irregular target movement",
        advancedTips: "Advanced Tips",
        windCompensation: "Wind Compensation",
        windCompensationDesc: "Observe wind indicator direction and strength",
        movingTargetPrediction: "Moving Target Prediction",
        movingTargetPredictionDesc: "Study target movement patterns",
        perfectChargeTiming: "Perfect Charge Timing",
        perfectChargeTimingDesc: "Special sound indicates optimal charge position",
        scoringSystem: "Scoring System",
        basicScoring: "Basic Scoring",
        basicScoringDesc: "Hit apple: 100 points",
        comboRewards: "Combo Rewards",
        comboRewardsDesc: "2 hits: 1.2x multiplier",
        specialRewards: "Special Rewards",
        specialRewardsDesc: "Double hit: +200 points",
        achievements: "Achievements",
        noviceAchievements: "Novice Achievements",
        noviceAchievementsDesc: "First Hit: Complete first successful shot",
        advancedAchievements: "Advanced Achievements",
        advancedAchievementsDesc: "Intermediate Archer: Complete first 10 levels",
        masterAchievements: "Master Achievements",
        masterAchievementsDesc: "Archery Master: Complete all levels",
        
        // Gameplay Page
        howToPlay: "How to Play",
        startGame: "Start the Game",
        startGameDesc: "Click the 'Play Now' button to start your AppleShooter adventure. The game will begin with a tutorial level to help you get familiar with the controls.",
        controls: "Controls",
        controlsDesc: "Use your mouse to aim and click to shoot. The apples will appear at different positions and speeds. Your goal is to hit as many apples as possible.",
        scoring: "Scoring",
        scoringDesc: "Each apple you hit gives you points. The faster you hit the apple, the more points you earn. Special golden apples give bonus points!",
        powerUps: "Power-ups",
        powerUpsDesc: "Collect power-ups to enhance your shooting abilities. These include time slowers, multi-shots, and score multipliers.",
        levels: "Levels",
        levelsDesc: "Progress through increasingly challenging levels. Each level introduces new obstacles and faster apples to test your skills.",
        proTips: "Pro Tips",
        aimAhead: "Aim Ahead",
        aimAheadDesc: "Anticipate the apple's movement and aim slightly ahead of its current position.",
        timingIsKey: "Timing is Key",
        timingIsKeyDesc: "Wait for the perfect moment to shoot for maximum points.",
        powerUpStrategy: "Power-up Strategy",
        powerUpStrategyDesc: "Save power-ups for difficult levels or when you're going for high scores.",
        
        // Music Page
        mainTheme: "Main Theme",
        mainThemeDesc: "The iconic main theme of AppleShooter",
        level1Music: "Level 1: Beginner's Luck",
        level1MusicDesc: "Upbeat and encouraging music for the first level",
        bossBattleTheme: "Boss Battle Theme",
        bossBattleThemeDesc: "Intense music for epic boss battles",
        victoryTheme: "Victory Theme",
        victoryThemeDesc: "Celebratory music for completing levels",
        menuTheme: "Menu Theme",
        menuThemeDesc: "Relaxing background music for the main menu",
        downloadText: "Download",
        
        // Talk Page
        gameDiscussion: "Game Discussion",
        addComment: "Add Your Comment",
        username: "Username",
        comment: "Comment",
        postComment: "Post Comment",
        recentComments: "Recent Comments",
        totalComments: "Total: 45 comments",
        deleteComment: "Delete",
        
        // Footer
        contactUs: "Contact Us:",
        
        // Screenshots Page
        loadingScreen: "Loading Screen",
        loadingScreenDesc: "The game's loading screen featuring the iconic AppleShooter logo and a dynamic loading animation.",
        startScreen: "Start Screen",
        startScreenDesc: "The main menu screen where players can begin their archery adventure.",
        gameplayScreen: "Gameplay Screen",
        gameplayScreenDesc: "The main gameplay interface showing the archery target and aiming system.",
        successScreen: "Success Screen",
        successScreenDesc: "The victory screen that appears when players successfully hit their target.",
        failedScreen: "Failed Screen",
        failedScreenDesc: "The screen that appears when players miss their target, encouraging them to try again."
    },
    zh: {
        // Navigation
        home: "首页",
        gameIntro: "游戏介绍",
        media: "媒体",
        guide: "攻略",
        talk: "讨论",
        
        // Game Intro Page
        gameTitle: "AppleShooter - 经典射击游戏",
        gameDescription: "AppleShooter是一款充满挑战性的射击游戏，玩家需要使用弓箭精确射击放在人头上的苹果。游戏考验玩家的准确性、耐心和技巧，每一箭都可能带来胜利或失败。",
        gameplay: "游戏玩法",
        basicControls: "基本操作",
        basicControlsDesc: "使用鼠标瞄准：移动鼠标来调整弓箭的方向",
        chargeControl: "按住鼠标左键：蓄力，箭的威力随按住时间增加",
        fireControl: "松开鼠标左键：发射箭",
        gameObjectives: "游戏目标",
        gameObjectivesDesc: "准确射中苹果，避免击中人物",
        levelDifficulty: "每个关卡都有不同的难度和挑战",
        highScore: "通过精准射击获得高分",
        gameFeatures: "游戏特色",
        gameFeaturesDesc: "物理引擎：真实的箭矢飞行轨迹",
        increasingDifficulty: "递增难度：游戏难度逐渐增加",
        instantFeedback: "即时反馈：直观的击中效果",
        gameHistory: "游戏历史",
        gameHistoryDesc: "AppleShooter的灵感来源于瑞士民间传说中的英雄威廉·退尔。",
        developmentTeam: "创作团队",
        developmentTeamDesc: "AppleShooter由一支充满激情的游戏开发团队打造。",
        developmentHistory: "开发历史",
        history2005: "2005年：游戏概念诞生，开始早期开发",
        history2006: "2006年：首个Flash版本发布",
        history2010: "2010年：改进版本发布，新增游戏机制",
        history2015: "2015年：HTML5版本发布，支持移动设备",
        history2020: "2020年：重大升级，优化游戏体验",
        coreTeam: "核心团队",
        gameDesign: "游戏设计：",
        gameDesigner: "约翰·史密斯 - 资深游戏设计师，拥有10年休闲游戏开发经验",
        programming: "编程：",
        programmer: "莎拉·约翰逊 - 首席程序员，专注于物理引擎优化",
        artDesign: "美术设计：",
        artist: "迈克尔·陈 - 资深游戏美术师，负责视觉风格设计",
        soundDesign: "音效设计：",
        soundDesigner: "丽莎·王 - 音效设计师，创作游戏音乐和音效",
        
        // Media Page
        gameMedia: "游戏媒体",
        gameScreenshots: "游戏截图",
        gameScreenshotsDesc: "查看精彩的游戏瞬间",
        gameMusic: "游戏音乐",
        gameMusicDesc: "聆听游戏原声",
        gameVideos: "游戏视频",
        gameVideosDesc: "观看游戏视频",
        
        // Guide Page
        basicControlsGuide: "基本操作指南",
        aimingSystem: "瞄准系统",
        aimingSystemDesc: "使用鼠标移动来调整弓箭瞄准方向",
        shootingMechanism: "射击机制",
        shootingMechanismDesc: "按住鼠标左键蓄力",
        specialTechniques: "特殊技巧",
        specialTechniquesDesc: "快速点击：快速点击进行快速射击",
        levelGuide: "关卡攻略",
        beginnerLevels: "初级关卡 (1-5)",
        beginnerLevelsDesc: "静止目标，近距离",
        intermediateLevels: "中级关卡 (6-10)",
        intermediateLevelsDesc: "缓慢移动的目标",
        advancedLevels: "高级关卡 (11-15)",
        advancedLevelsDesc: "快速移动的目标",
        ultimateLevels: "终极关卡 (16-20)",
        ultimateLevelsDesc: "不规则移动的目标",
        advancedTips: "高级技巧",
        windCompensation: "风力补偿",
        windCompensationDesc: "观察风向指示器的方向和强度",
        movingTargetPrediction: "移动目标预测",
        movingTargetPredictionDesc: "研究目标的移动模式",
        perfectChargeTiming: "完美蓄力时机",
        perfectChargeTimingDesc: "特殊声音表示最佳蓄力位置",
        scoringSystem: "得分系统",
        basicScoring: "基本得分",
        basicScoringDesc: "击中苹果：100分",
        comboRewards: "连击奖励",
        comboRewardsDesc: "2次连击：1.2倍倍率",
        specialRewards: "特殊奖励",
        specialRewardsDesc: "双倍命中：+200分",
        achievements: "成就系统",
        noviceAchievements: "新手成就",
        noviceAchievementsDesc: "首次命中：完成第一次成功射击",
        advancedAchievements: "进阶成就",
        advancedAchievementsDesc: "中级射手：完成前10关",
        masterAchievements: "大师成就",
        masterAchievementsDesc: "射箭大师：完成所有关卡",
        
        // Gameplay Page
        howToPlay: "如何游戏",
        startGame: "开始游戏",
        startGameDesc: "点击立即游戏按钮开始你的AppleShooter冒险。游戏将从教程关卡开始，帮助你熟悉操作。",
        controls: "操作",
        controlsDesc: "使用鼠标瞄准并点击射击。苹果会出现在不同的位置和速度。你的目标是击中尽可能多的苹果。",
        scoring: "得分",
        scoringDesc: "每击中一个苹果都会获得分数。击中苹果的速度越快，获得的分数越多。特殊的金色苹果会给予额外分数！",
        powerUps: "强化道具",
        powerUpsDesc: "收集强化道具来增强你的射击能力。这些包括时间减速器、多重射击和分数倍增器。",
        levels: "关卡",
        levelsDesc: "通过越来越具有挑战性的关卡。每个关卡都会引入新的障碍和更快的苹果来测试你的技能。",
        proTips: "专业技巧",
        aimAhead: "提前瞄准",
        aimAheadDesc: "预测苹果的移动并稍微提前瞄准其当前位置。",
        timingIsKey: "时机是关键",
        timingIsKeyDesc: "等待最佳时机射击以获得最高分数。",
        powerUpStrategy: "强化道具策略",
        powerUpStrategyDesc: "将强化道具留到困难关卡或追求高分时使用。",
        
        // Music Page
        mainTheme: "主题曲",
        mainThemeDesc: "AppleShooter的标志性主题曲",
        level1Music: "第一关：新手运气",
        level1MusicDesc: "第一关的欢快和鼓舞人心的音乐",
        bossBattleTheme: "Boss战主题曲",
        bossBattleThemeDesc: "史诗级Boss战的紧张音乐",
        victoryTheme: "胜利主题曲",
        victoryThemeDesc: "完成关卡的庆祝音乐",
        menuTheme: "菜单主题曲",
        menuThemeDesc: "主菜单的轻松背景音乐",
        downloadText: "下载",
        
        // Talk Page
        gameDiscussion: "游戏讨论",
        addComment: "添加评论",
        username: "用户名",
        comment: "评论",
        postComment: "发表评论",
        recentComments: "最新评论",
        totalComments: "总计：45条评论",
        deleteComment: "删除",
        
        // Footer
        contactUs: "联系我们：",
        
        // Screenshots Page
        loadingScreen: "加载界面",
        loadingScreenDesc: "游戏加载界面，展示 AppleShooter 标志性 logo 和动态加载动画。",
        startScreen: "开始界面",
        startScreenDesc: "主菜单界面，玩家可以在这里开始他们的射箭冒险。",
        gameplayScreen: "游戏界面",
        gameplayScreenDesc: "主要游戏界面，展示射箭目标和瞄准系统。",
        successScreen: "成功界面",
        successScreenDesc: "当玩家成功击中目标时显示的胜利界面。",
        failedScreen: "失败界面",
        failedScreenDesc: "当玩家未击中目标时显示的界面，鼓励玩家再次尝试。"
    },
    ja: {
        // Navigation
        home: "ホーム",
        gameIntro: "ゲーム紹介",
        media: "メディア",
        guide: "ガイド",
        talk: "トーク",
        
        // Game Intro Page
        gameTitle: "AppleShooter - クラシックシューティングゲーム",
        gameDescription: "AppleShooterは、プレイヤーが弓と矢を使って人の頭の上のリンゴを正確に射抜く必要がある挑戦的なシューティングゲームです。ゲームはプレイヤーの正確性、忍耐力、スキルを試し、一発一発が勝利か敗北をもたらす可能性があります。",
        gameplay: "ゲームプレイ",
        basicControls: "基本操作",
        basicControlsDesc: "マウスで照準を合わせる：マウスを動かして矢の方向を調整",
        chargeControl: "マウスの左ボタンを長押し：チャージ、押している時間に応じて矢の威力が増加",
        fireControl: "マウスの左ボタンを離す：矢を発射",
        gameObjectives: "ゲーム目標",
        gameObjectivesDesc: "リンゴを正確に当て、人に当たらないようにする",
        levelDifficulty: "各レベルに異なる難易度とチャレンジがある",
        highScore: "正確な射撃でハイスコアを獲得",
        gameFeatures: "ゲーム特徴",
        gameFeaturesDesc: "物理エンジン：リアルな矢の軌道",
        increasingDifficulty: "難易度上昇：ゲームの難易度が徐々に増加",
        instantFeedback: "即時フィードバック：直感的な命中効果",
        gameHistory: "ゲームの歴史",
        gameHistoryDesc: "AppleShooterのインスピレーションは、スイスの民間伝説の英雄ウィリアム・テルから来ています。",
        developmentTeam: "開発チーム",
        developmentTeamDesc: "AppleShooterは情熱的なゲーム開発チームによって作られました。",
        developmentHistory: "開発履歴",
        history2005: "2005年：ゲームコンセプト誕生、初期開発開始",
        history2006: "2006年：最初のFlashバージョンリリース",
        history2010: "2010年：改善版リリース、新ゲームメカニクス追加",
        history2015: "2015年：HTML5バージョンリリース、モバイルデバイス対応",
        history2020: "2020年：大規模アップグレード、ゲーム体験の最適化",
        coreTeam: "コアチーム",
        gameDesign: "ゲームデザイン：",
        gameDesigner: "ジョン・スミス - 10年のカジュアルゲーム開発経験を持つシニアゲームデザイナー",
        programming: "プログラミング：",
        programmer: "サラ・ジョンソン - 物理エンジンの最適化に焦点を当てたリードプログラマー",
        artDesign: "アートデザイン：",
        artist: "マイケル・チェン - 時間スタイルデザインを担当するシニアゲームアーティスト",
        soundDesign: "サウンドデザイン：",
        soundDesigner: "リサ・ワン - ゲーム音楽とサウンドエフェクトを作成するサウンドデザイナー",
        
        // Media Page
        gameMedia: "ゲームメディア",
        gameScreenshots: "ゲームスクリーンショット",
        gameScreenshotsDesc: "素晴らしいゲーム内の瞬間を見る",
        gameMusic: "ゲーム音楽",
        gameMusicDesc: "ゲームサウンドトラックを聴く",
        gameVideos: "ゲーム動画",
        gameVideosDesc: "ゲームプレイ動画を見る",
        
        // Guide Page
        basicControlsGuide: "基本操作ガイド",
        aimingSystem: "照準システム",
        aimingSystemDesc: "マウスの動きで弓の照準を調整",
        shootingMechanism: "射撃メカニズム",
        shootingMechanismDesc: "マウスの左ボタンを押し続けてチャージ",
        specialTechniques: "特殊テクニック",
        specialTechniquesDesc: "クイッククリック：素早いクリックで連続射撃",
        levelGuide: "レベルガイド",
        beginnerLevels: "初級レベル (1-5)",
        beginnerLevelsDesc: "静止したターゲット、近距離",
        intermediateLevels: "中級レベル (6-10)",
        intermediateLevelsDesc: "ゆっくり動くターゲット",
        advancedLevels: "上級レベル (11-15)",
        advancedLevelsDesc: "速く動くターゲット",
        ultimateLevels: "究極レベル (16-20)",
        ultimateLevelsDesc: "不規則に動くターゲット",
        advancedTips: "上級者向けヒント",
        windCompensation: "風の補正",
        windCompensationDesc: "風向きインジケーターの方向と強さを観察",
        movingTargetPrediction: "移動ターゲットの予測",
        movingTargetPredictionDesc: "ターゲットの動きのパターンを研究",
        perfectChargeTiming: "完璧なチャージタイミング",
        perfectChargeTimingDesc: "特殊音で最適なチャージ位置を知らせる",
        scoringSystem: "スコアリングシステム",
        basicScoring: "基本スコア",
        basicScoringDesc: "リンゴを当てる：100ポイント",
        comboRewards: "コンボ報酬",
        comboRewardsDesc: "2回連続：1.2倍ボーナス",
        specialRewards: "特別報酬",
        specialRewardsDesc: "ダブルヒット：+200ポイント",
        achievements: "実績システム",
        noviceAchievements: "初心者実績",
        noviceAchievementsDesc: "初めての命中：最初の成功した射撃を完了",
        advancedAchievements: "上級者実績",
        advancedAchievementsDesc: "中級射手：最初の10レベルを完了",
        masterAchievements: "マスター実績",
        masterAchievementsDesc: "弓術マスター：すべてのレベルを完了",
        
        // Gameplay Page
        howToPlay: "遊び方",
        startGame: "ゲーム開始",
        startGameDesc: "「今すぐプレイ」ボタンをクリックしてAppleShooterの冒険を始めましょう。ゲームはチュートリアルレベルから始まり、操作に慣れるのに役立ちます。",
        controls: "操作",
        controlsDesc: "マウスで照準を合わせ、クリックして射撃します。リンゴは様々な位置と速度で現れます。できるだけ多くのリンゴを当てるのが目標です。",
        scoring: "スコア",
        scoringDesc: "リンゴを当てるごとにポイントが入ります。リンゴを当てるのが速いほど、より多くのポイントが入ります。特別な金色のリンゴはボーナスポイントを与えます！",
        powerUps: "パワーアップ",
        powerUpsDesc: "パワーアップを集めて射撃能力を強化します。これには時間遅延、マルチショット、スコア倍増器が含まれます。",
        levels: "レベル",
        levelsDesc: "ますます挑戦的なレベルを進んでいきます。各レベルでは新しい障害物やより速いリンゴが導入され、スキルが試されます。",
        proTips: "プロのヒント",
        aimAhead: "先読み照準",
        aimAheadDesc: "リンゴの動きを予測し、現在の位置より少し先を狙います。",
        timingIsKey: "タイミングが重要",
        timingIsKeyDesc: "最高得点を得るために最適な瞬間を待って射撃します。",
        powerUpStrategy: "パワーアップ戦略",
        powerUpStrategyDesc: "パワーアップは難しいレベルやハイスコアをノリします。",
        
        // Music Page
        mainTheme: "メインテーマ",
        mainThemeDesc: "AppleShooterの象徴的なメインテーマ",
        level1Music: "レベル1：初心者の幸運",
        level1MusicDesc: "最初のレベルの明るく励みになる音楽",
        bossBattleTheme: "ボス戦テーマ",
        bossBattleThemeDesc: "壮大なボス戦の緊張感ある音楽",
        victoryTheme: "勝利テーマ",
        victoryThemeDesc: "レベルクリアの祝福の音楽",
        menuTheme: "メニューテーマ",
        menuThemeDesc: "メインメニューのリラックスできるBGM",
        downloadText: "ダウンロード",
        
        // Talk Page
        gameDiscussion: "ゲームディスカッション",
        addComment: "コメントを追加",
        username: "ユーザー名",
        comment: "コメント",
        postComment: "コメントを投稿",
        recentComments: "最近のコメント",
        totalComments: "合計：45件のコメント",
        deleteComment: "削除",
        
        // Footer
        contactUs: "お問い合わせ：",
        
        // Screenshots Page
        loadingScreen: "ローディング画面",
        loadingScreenDesc: "AppleShooterの象徴的なロゴと動的なローディングアニメーションを特徴とするローディング画面。",
        startScreen: "スタート画面",
        startScreenDesc: "プレイヤーがアーチェリーの冒険を始めることができるメインメニュー画面。",
        gameplayScreen: "ゲームプレイ画面",
        gameplayScreenDesc: "アーチェリーのターゲットと照準システムを表示するメインゲームプレイインターフェース。",
        successScreen: "成功画面",
        successScreenDesc: "プレイヤーがターゲットを成功裏にヒットしたときに表示される勝利画面。",
        failedScreen: "失敗画面",
        failedScreenDesc: "プレイヤーがターゲットを外したときに表示される画面で、再挑戦を促します。"
    },
    ko: {
        // Navigation
        home: "홈",
        gameIntro: "게임 소개",
        media: "미디어",
        guide: "가이드",
        talk: "토론",
        
        // Game Intro Page
        gameTitle: "AppleShooter - 클래식 슈팅 게임",
        gameDescription: "AppleShooter는 플레이어가 활과 화살을 사용하여 사람의 머리 위에 놓인 사과를 정확하게 쏘아야 하는 도전적인 슈팅 게임입니다. 게임은 플레이어의 정확성, 인내심, 기술을 테스트하며, 각 발사가 승리나 패배를 가져올 수 있습니다.",
        gameplay: "게임플레이",
        basicControls: "기본 조작",
        basicControlsDesc: "마우스로 조준: 마우스를 이동하여 화살의 방향을 조정",
        chargeControl: "마우스 왼쪽 버튼 길게 누르기: 충전, 누르는 시간에 따라 화살 위력 증가",
        fireControl: "마우스 왼쪽 버튼 놓기: 화살 발사",
        gameObjectives: "게임 목표",
        gameObjectivesDesc: "사과를 정확하게 맞추고, 사람을 맞추지 않기",
        levelDifficulty: "각 레벨마다 다른 난이도와 도전이 있습니다",
        highScore: "정확한 사격으로 고득점 획득",
        gameFeatures: "게임 특징",
        gameFeaturesDesc: "물리 엔진: 현실적인 화살 비행 궤적",
        increasingDifficulty: "난이도 증가: 게임 난이도가 점진적으로 증가",
        instantFeedback: "즉각적인 피드백: 직관적인 명중 효과",
        gameHistory: "게임 역사",
        gameHistoryDesc: "AppleShooter의 영감은 스위스 민간 전설의 영웅 윌리엄 텔에서 비롯되었습니다.",
        developmentTeam: "개발 팀",
        developmentTeamDesc: "AppleShooter는 열정적인 게임 개발 팀에 의해 만들어졌습니다.",
        developmentHistory: "개발 역사",
        history2005: "2005년: 게임 컨셉 탄생, 초기 개발 시작",
        history2006: "2006년: 첫 Flash 버전 출시",
        history2010: "2010년: 개선된 버전 출시, 새로운 게임 메커니즘 추가",
        history2015: "2015년: HTML5 버전 출시, 모바일 기기 지원",
        history2020: "2020년: 대규모 업그레이드, 게임 경험 최적화",
        coreTeam: "핵심 팀",
        gameDesign: "게임 디자인:",
        gameDesigner: "존 스미스 - 10년 경력의 캐주얼 게임 개발 경험을 가진 시니어 게임 디자이너",
        programming: "프로그래밍:",
        programmer: "사라 존슨 - 물리 엔진 최적화에 중점을 둔 리드 프로그래머",
        artDesign: "아트 디자인:",
        artist: "마이클 첸 - 시각 스타일 디자인을 담당하는 시니어 게임 아티스트",
        soundDesign: "사운드 디자인:",
        soundDesigner: "리사 왕 - 게임 음악과 사운드 효과를 만드는 사운드 디자이너",
        
        // Media Page
        gameMedia: "게임 미디어",
        gameScreenshots: "게임 스크린샷",
        gameScreenshotsDesc: "멋진 게임 내 순간을 보기",
        gameMusic: "게임 음악",
        gameMusicDesc: "게임 사운드트랙 듣기",
        gameVideos: "게임 비디오",
        gameVideosDesc: "게임플레이 비디오 보기",
        
        // Guide Page
        basicControlsGuide: "기본 조작 가이드",
        aimingSystem: "조준 시스템",
        aimingSystemDesc: "마우스 움직임으로 활 조준 방향 조정",
        shootingMechanism: "사격 메커니즘",
        shootingMechanismDesc: "마우스 왼쪽 버튼을 누르고 있으면 충전",
        specialTechniques: "특수 기술",
        specialTechniquesDesc: "빠른 클릭: 빠른 클릭으로 연속 사격",
        levelGuide: "레벨 가이드",
        beginnerLevels: "초급 레벨 (1-5)",
        beginnerLevelsDesc: "고정된 표적, 근거리",
        intermediateLevels: "중급 레벨 (6-10)",
        intermediateLevelsDesc: "천천히 움직이는 표적",
        advancedLevels: "고급 레벨 (11-15)",
        advancedLevelsDesc: "빠르게 움직이는 표적",
        ultimateLevels: "궁극 레벨 (16-20)",
        ultimateLevelsDesc: "불규칙하게 움직이는 표적",
        advancedTips: "고급 팁",
        windCompensation: "바람 보정",
        windCompensationDesc: "바람 방향 표시기의 방향과 강도 관찰",
        movingTargetPrediction: "이동 표적 예측",
        movingTargetPredictionDesc: "표적의 움직임 패턴 연구",
        perfectChargeTiming: "완벽한 충전 타이밍",
        perfectChargeTimingDesc: "특수 소리로 최적의 충전 위치 알림",
        scoringSystem: "점수 시스템",
        basicScoring: "기본 점수",
        basicScoringDesc: "사과 맞추기: 100점",
        comboRewards: "콤보 보상",
        comboRewardsDesc: "2연속: 1.2배 보너스",
        specialRewards: "특별 보상",
        specialRewardsDesc: "더블 히트: +200점",
        achievements: "업적 시스템",
        noviceAchievements: "초보자 업적",
        noviceAchievementsDesc: "첫 번째 명중: 첫 번째 성공적인 사격 완료",
        advancedAchievements: "고급 업적",
        advancedAchievementsDesc: "중급 궁수: 첫 10레벨 완료",
        masterAchievements: "마스터 업적",
        masterAchievementsDesc: "궁술 마스터: 모든 레벨 완료",
        
        // Gameplay Page
        howToPlay: "게임 방법",
        startGame: "게임 시작",
        startGameDesc: "'지금 플레이' 버튼을 클릭하여 AppleShooter 모험을 시작하세요. 게임은 튜토리얼 레벨로 시작하여 조작에 익숙해지는 데 도움이 됩니다.",
        controls: "조작",
        controlsDesc: "마우스로 조준하고 클릭하여 사격합니다. 사과는 다양한 위치와 속도로 나타납니다. 목표는 가능한 많은 사과를 맞추는 것입니다.",
        scoring: "점수",
        scoringDesc: "사과를 맞출 때마다 점수를 얻습니다. 사과를 더 빨리 맞출수록 더 많은 점수를 얻습니다. 특별한 황금 사과는 보너스 점수를 줍니다!",
        powerUps: "파워업",
        powerUpsDesc: "파워업을 수집하여 사격 능력을 향상시킵니다. 여기에는 시간 감속기, 다중 사격, 점수 배가기가 포함됩니다.",
        levels: "레벨",
        levelsDesc: "점점 더 도전적인 레벨을 진행합니다. 각 레벨은 새로운 장애물과 더 빠른 사과를 도입하여 기술을 시험합니다.",
        proTips: "프로 팁",
        aimAhead: "앞서 조준",
        aimAheadDesc: "사과의 움직임을 예측하고 현재 위치보다 약간 앞을 조준합니다.",
        timingIsKey: "타이밍이 중요",
        timingIsKeyDesc: "최고 점수를 얻기 위해 완벽한 순간을 기다립니다.",
        powerUpStrategy: "파워업 전략",
        powerUpStrategyDesc: "파워업은 어려운 레벨이나 하이스코어를 노릴 때 아껴둡니다.",
        
        // Music Page
        mainTheme: "메인 테마",
        mainThemeDesc: "AppleShooter의 상징적인 메인 테마",
        level1Music: "레벨 1: 초보자의 행운",
        level1MusicDesc: "첫 번째 레벨의 경쾌하고 격려하는 음악",
        bossBattleTheme: "보스전 테마",
        bossBattleThemeDesc: "장엄한 보스전의 긴장감 있는 음악",
        victoryTheme: "승리 테마",
        victoryThemeDesc: "레벨 완료의 축하 음악",
        menuTheme: "메뉴 테마",
        menuThemeDesc: "메인 메뉴의 편안한 배경 음악",
        downloadText: "다운로드",
        
        // Talk Page
        gameDiscussion: "게임 토론",
        addComment: "댓글 추가",
        username: "사용자 이름",
        comment: "댓글",
        postComment: "댓글 작성",
        recentComments: "최근 댓글",
        totalComments: "총계: 45개의 댓글",
        deleteComment: "삭제",
        
        // Footer
        contactUs: "문의하기:",
        
        // Screenshots Page
        loadingScreen: "로딩 화면",
        loadingScreenDesc: "AppleShooter의 상징적인 로고와 동적 로딩 애니메이션이 특징인 게임 로딩 화면입니다.",
        startScreen: "시작 화면",
        startScreenDesc: "플레이어가 양궁 모험을 시작할 수 있는 메인 메뉴 화면입니다.",
        gameplayScreen: "게임플레이 화면",
        gameplayScreenDesc: "양궁 표적과 조준 시스템을 보여주는 메인 게임플레이 인터페이스입니다.",
        successScreen: "성공 화면",
        successScreenDesc: "플레이어가 목표물을 성공적으로 맞췄을 때 나타나는 승리 화면입니다.",
        failedScreen: "실패 화면",
        failedScreenDesc: "플레이어가 목표물을 놓쳤을 때 나타나는 화면으로, 다시 시도하도록 격려합니다."
    },
    es: {
        // Navigation
        home: "Inicio",
        gameIntro: "Introducción al Juego",
        media: "Medios",
        guide: "Guía",
        talk: "Discusión",
        
        // Game Intro Page
        gameTitle: "AppleShooter - Juego de Disparos Clásico",
        gameDescription: "AppleShooter es un desafiante juego de disparos donde los jugadores deben usar un arco y flecha para disparar con precisión a manzanas colocadas en la cabeza de las personas. El juego pone a prueba la precisión, paciencia y habilidad de los jugadores, donde cada disparo puede traer victoria o derrota.",
        gameplay: "Jugabilidad",
        basicControls: "Controles Básicos",
        basicControlsDesc: "Usa el mouse para apuntar: Mueve el mouse para ajustar la dirección de la flecha",
        chargeControl: "Mantén presionado el botón izquierdo del mouse: Carga, el poder de la flecha aumenta con el tiempo de presión",
        fireControl: "Suelta el botón izquierdo del mouse: Dispara la flecha",
        gameObjectives: "Objetivos del Juego",
        gameObjectivesDesc: "Golpea con precisión la manzana, evita golpear a la persona",
        levelDifficulty: "Cada nivel tiene diferentes dificultades y desafíos",
        highScore: "Obtén puntuaciones altas a través de disparos precisos",
        gameFeatures: "Características del Juego",
        gameFeaturesDesc: "Motor físico: Trayectoria realista de vuelo de flechas",
        increasingDifficulty: "Dificultad creciente: La dificultad del juego aumenta gradualmente",
        instantFeedback: "Retroalimentación instantánea: Efectos de impacto intuitivos",
        gameHistory: "Historia del Juego",
        gameHistoryDesc: "La inspiración para AppleShooter proviene de la leyenda popular suiza de Guillermo Tell.",
        developmentTeam: "Equipo de Desarrollo",
        developmentTeamDesc: "AppleShooter es creado por un apasionado equipo de desarrollo de juegos.",
        developmentHistory: "Historia de Desarrollo",
        history2005: "2005: Nace el concepto del juego, comienza el desarrollo temprano",
        history2006: "2006: Se lanza la primera versión en Flash",
        history2010: "2010: Se lanza la versión mejorada con nuevas mecánicas de juego",
        history2015: "2015: Se lanza la versión HTML5, compatible con dispositivos móviles",
        history2020: "2020: Actualización importante, optimizando la experiencia de juego",
        coreTeam: "Equipo Central",
        gameDesign: "Diseño del Juego:",
        gameDesigner: "John Smith - Diseñador de juegos senior con 10 años de experiencia en desarrollo de juegos casuales",
        programming: "Programación:",
        programmer: "Sarah Johnson - Programadora principal, enfocada en la optimización del motor físico",
        artDesign: "Diseño Artístico:",
        artist: "Michael Chen - Artista de juegos senior, responsable del diseño del estilo visual",
        soundDesign: "Diseño de Sonido:",
        soundDesigner: "Lisa Wang - Diseñadora de sonido, creando música y efectos de sonido para el juego",
        
        // Media Page
        gameMedia: "Medios del Juego",
        gameScreenshots: "Capturas de Pantalla",
        gameScreenshotsDesc: "Ver momentos increíbles del juego",
        gameMusic: "Música del Juego",
        gameMusicDesc: "Escuchar la banda sonora",
        gameVideos: "Videos del Juego",
        gameVideosDesc: "Ver videos de gameplay",
        
        // Guide Page
        basicControlsGuide: "Guía de Controles Básicos",
        aimingSystem: "Sistema de Apuntado",
        aimingSystemDesc: "Usa el movimiento del mouse para ajustar la dirección del arco",
        shootingMechanism: "Mecanismo de Disparo",
        shootingMechanismDesc: "Mantén presionado el botón izquierdo del mouse para cargar",
        specialTechniques: "Técnicas Especiales",
        specialTechniquesDesc: "Clic Rápido: Clics rápidos para disparos rápidos",
        levelGuide: "Guía de Niveles",
        beginnerLevels: "Niveles Principiantes (1-5)",
        beginnerLevelsDesc: "Objetivos estacionarios, corta distancia",
        intermediateLevels: "Niveles Intermedios (6-10)",
        intermediateLevelsDesc: "Objetivos en movimiento lento",
        advancedLevels: "Niveles Avanzados (11-15)",
        advancedLevelsDesc: "Objetivos en movimiento rápido",
        ultimateLevels: "Niveles Definitivos (16-20)",
        ultimateLevelsDesc: "Objetivos en movimiento irregular",
        advancedTips: "Consejos Avanzados",
        windCompensation: "Compensación del Viento",
        windCompensationDesc: "Observa la dirección y fuerza del indicador de viento",
        movingTargetPrediction: "Predicción de Objetivos en Movimiento",
        movingTargetPredictionDesc: "Estudia los patrones de movimiento del objetivo",
        perfectChargeTiming: "Momento Perfecto de Carga",
        perfectChargeTimingDesc: "Un sonido especial indica la posición óptima de carga",
        scoringSystem: "Sistema de Puntuación",
        basicScoring: "Puntuación Básica",
        basicScoringDesc: "Golpear manzana: 100 puntos",
        comboRewards: "Recompensas de Combo",
        comboRewardsDesc: "2 golpes: multiplicador 1.2x",
        specialRewards: "Recompensas Especiales",
        specialRewardsDesc: "Doble golpe: +200 puntos",
        achievements: "Logros",
        noviceAchievements: "Logros de Novato",
        noviceAchievementsDesc: "Primer Golpe: Completa el primer disparo exitoso",
        advancedAchievements: "Logros Avanzados",
        advancedAchievementsDesc: "Arquero Intermedio: Completa los primeros 10 niveles",
        masterAchievements: "Logros de Maestro",
        masterAchievementsDesc: "Maestro del Tiro con Arco: Completa todos los niveles",
        
        // Gameplay Page
        howToPlay: "Cómo Jugar",
        startGame: "Iniciar el Juego",
        startGameDesc: "Haz clic en el botón 'Jugar Ahora' para comenzar tu aventura en AppleShooter. El juego comenzará con un nivel tutorial para ayudarte a familiarizarte con los controles.",
        controls: "Controles",
        controlsDesc: "Usa el mouse para apuntar y haz clic para disparar. Las manzanas aparecerán en diferentes posiciones y velocidades. Tu objetivo es golpear tantas manzanas como sea posible.",
        scoring: "Puntuación",
        scoringDesc: "Cada manzana que golpees te da puntos. Cuanto más rápido golpees la manzana, más puntos ganarás. ¡Las manzanas doradas especiales dan puntos extra!",
        powerUps: "Mejoras",
        powerUpsDesc: "Recoge mejoras para potenciar tus habilidades de disparo. Estas incluyen ralentizadores de tiempo, disparos múltiples y multiplicadores de puntuación.",
        levels: "Niveles",
        levelsDesc: "Progresa a través de niveles cada vez más desafiantes. Cada nivel introduce nuevos obstáculos y manzanas más rápidas para poner a prueba tus habilidades.",
        proTips: "Consejos Profesionales",
        aimAhead: "Apuntar Adelante",
        aimAheadDesc: "Anticipa el movimiento de la manzana y apunta ligeramente por delante de su posición actual.",
        timingIsKey: "El Momento es Clave",
        timingIsKeyDesc: "Espera el momento perfecto para disparar y obtener la máxima puntuación.",
        powerUpStrategy: "Estrategia de Mejoras",
        powerUpStrategyDesc: "Guarda las mejoras para niveles difíciles o cuando busques puntuaciones altas.",
        
        // Music Page
        mainTheme: "Tema Principal",
        mainThemeDesc: "El icónico tema principal de AppleShooter",
        level1Music: "Nivel 1: Suerte de Principiante",
        level1MusicDesc: "Música animada y alentadora para el primer nivel",
        bossBattleTheme: "Tema de Batalla contra Jefe",
        bossBattleThemeDesc: "Música intensa para batallas épicas contra jefes",
        victoryTheme: "Tema de Victoria",
        victoryThemeDesc: "Música celebratoria por completar niveles",
        menuTheme: "Tema del Menú",
        menuThemeDesc: "Música relajante para el menú principal",
        downloadText: "Descargar",
        
        // Talk Page
        gameDiscussion: "Discusión del Juego",
        addComment: "Añadir Comentario",
        username: "Nombre de Usuario",
        comment: "Comentario",
        postComment: "Publicar Comentario",
        recentComments: "Comentarios Recientes",
        totalComments: "Total: 45 comentarios",
        deleteComment: "Eliminar",
        
        // Footer
        contactUs: "Contáctanos:",
        
        // Screenshots Page
        loadingScreen: "Pantalla de Carga",
        loadingScreenDesc: "La pantalla de carga del juego presenta el icónico logo de AppleShooter y una animación de carga dinámica.",
        startScreen: "Pantalla de Inicio",
        startScreenDesc: "La pantalla del menú principal donde los jugadores pueden comenzar su aventura de tiro con arco.",
        gameplayScreen: "Pantalla de Juego",
        gameplayScreenDesc: "La interfaz principal del juego que muestra el objetivo de tiro con arco y el sistema de puntería.",
        successScreen: "Pantalla de Éxito",
        successScreenDesc: "La pantalla de victoria que aparece cuando los jugadores aciertan su objetivo.",
        failedScreen: "Pantalla de Fracaso",
        failedScreenDesc: "La pantalla que aparece cuando los jugadores fallan su objetivo, animándolos a intentarlo de nuevo."
    }
}; 