const languageData = {
    en: {
        // Navigation
        home: "Home",
        gameIntro: "Game Intro",
        media: "Media",
        guide: "Guide",
        talk: "Talk",
        
        // Game Intro Page
        gameTitle: "AppleShooter - Classic Shooting Game",
        gameDescription: "AppleShooter is a challenging shooting game where players must use a bow and arrow to precisely shoot apples placed on people's heads. The game tests players' accuracy, patience, and skill, with each shot potentially bringing victory or defeat.",
        gameplay: "Gameplay",
        basicControls: "Basic Controls",
        basicControlsDesc: "Use the mouse to aim: Move the mouse to adjust the direction of the arrow",
        chargeControl: "Hold left mouse button: Charge, arrow power increases with hold time",
        fireControl: "Release left mouse button: Fire the arrow",
        gameObjectives: "Game Objectives",
        gameObjectivesDesc: "Accurately hit the apple, avoid hitting the person",
        levelDifficulty: "Each level has different difficulties and challenges",
        highScore: "Get high scores through precise shooting",
        gameFeatures: "Game Features",
        gameFeaturesDesc: "Physics engine: Realistic arrow flight trajectory",
        increasingDifficulty: "Increasing difficulty: Gradually increasing game difficulty",
        instantFeedback: "Instant feedback: Intuitive hit effects",
        gameHistory: "Game History",
        gameHistoryDesc: "The inspiration for AppleShooter comes from the Swiss folk legend of William Tell.",
        developmentTeam: "Development Team",
        developmentTeamDesc: "AppleShooter is created by a passionate game development team.",
        developmentHistory: "Development History",
        history2005: "2005: Game concept born, early development started",
        history2006: "2006: First Flash version released",
        history2010: "2010: Improved version launched with new game mechanics",
        history2015: "2015: HTML5 version released, supporting mobile devices",
        history2020: "2020: Major upgrade, optimizing game experience",
        coreTeam: "Core Team",
        gameDesign: "Game Design:",
        gameDesigner: "John Smith - Senior game designer with 10 years of casual game development experience",
        programming: "Programming:",
        programmer: "Sarah Johnson - Lead programmer, focusing on physics engine optimization",
        artDesign: "Art Design:",
        artist: "Michael Chen - Senior game artist, responsible for visual style design",
        soundDesign: "Sound Design:",
        soundDesigner: "Lisa Wang - Sound designer, creating game music and sound effects",
        
        // Media Page
        gameMedia: "Game Media",
        gameScreenshots: "Game Screenshots",
        gameScreenshotsDesc: "View amazing in-game moments",
        gameMusic: "Game Music",
        gameMusicDesc: "Listen to the game soundtrack",
        gameVideos: "Game Videos",
        gameVideosDesc: "Watch gameplay videos",
        
        // Screenshots Page
        loadingScreen: "Loading Screen",
        loadingScreenDesc: "The game's loading screen featuring the iconic AppleShooter logo and a dynamic loading animation.",
        startScreen: "Start Screen",
        startScreenDesc: "The main menu screen where players can begin their archery adventure.",
        gameplayScreen: "Gameplay Screen",
        gameplayScreenDesc: "The main gameplay interface showing the archery target and aiming system.",
        successScreen: "Success Screen",
        successScreenDesc: "The victory screen that appears when players successfully hit their target.",
        failedScreen: "Failed Screen",
        failedScreenDesc: "The screen that appears when players miss their target, encouraging them to try again.",
        aimingSceneDesc: "Aiming Scene - Precise shooting angle calculation",
        hitEffectDesc: "Successful Hit - Arrow precisely hits the apple"
    },
    zh: {
        // Navigation
        home: "首页",
        gameIntro: "游戏介绍",
        media: "媒体",
        guide: "攻略",
        talk: "讨论",
        
        // Game Intro Page
        gameTitle: "AppleShooter - 经典射击游戏",
        gameDescription: "AppleShooter是一款充满挑战性的射击游戏，玩家需要使用弓箭精确射击放在人头上的苹果。游戏考验玩家的准确性、耐心和技巧，每一箭都可能带来胜利或失败。",
        gameplay: "游戏玩法",
        basicControls: "基本操作",
        basicControlsDesc: "使用鼠标瞄准：移动鼠标来调整弓箭的方向",
        chargeControl: "按住鼠标左键：蓄力，箭的威力随按住时间增加",
        fireControl: "松开鼠标左键：发射箭",
        gameObjectives: "游戏目标",
        gameObjectivesDesc: "准确射中苹果，避免击中人物",
        levelDifficulty: "每个关卡都有不同的难度和挑战",
        highScore: "通过精准射击获得高分",
        gameFeatures: "游戏特色",
        gameFeaturesDesc: "物理引擎：真实的箭矢飞行轨迹",
        increasingDifficulty: "递增难度：游戏难度逐渐增加",
        instantFeedback: "即时反馈：直观的击中效果",
        gameHistory: "游戏历史",
        gameHistoryDesc: "AppleShooter的灵感来源于瑞士民间传说中的英雄威廉·退尔。",
        developmentTeam: "创作团队",
        developmentTeamDesc: "AppleShooter由一支充满激情的游戏开发团队打造。",
        developmentHistory: "开发历史",
        history2005: "2005年：游戏概念诞生，开始早期开发",
        history2006: "2006年：首个Flash版本发布",
        history2010: "2010年：改进版本发布，新增游戏机制",
        history2015: "2015年：HTML5版本发布，支持移动设备",
        history2020: "2020年：重大升级，优化游戏体验",
        coreTeam: "核心团队",
        gameDesign: "游戏设计：",
        gameDesigner: "约翰·史密斯 - 资深游戏设计师，拥有10年休闲游戏开发经验",
        programming: "编程：",
        programmer: "莎拉·约翰逊 - 首席程序员，专注于物理引擎优化",
        artDesign: "美术设计：",
        artist: "迈克尔·陈 - 资深游戏美术师，负责视觉风格设计",
        soundDesign: "音效设计：",
        soundDesigner: "丽莎·王 - 音效设计师，创作游戏音乐和音效",
        
        // Media Page
        gameMedia: "游戏媒体",
        gameScreenshots: "游戏截图",
        gameScreenshotsDesc: "查看精彩的游戏瞬间",
        gameMusic: "游戏音乐",
        gameMusicDesc: "聆听游戏原声",
        gameVideos: "游戏视频",
        gameVideosDesc: "观看游戏视频",
        
        // Screenshots Page
        loadingScreen: "加载界面",
        loadingScreenDesc: "游戏加载界面，展示 AppleShooter 标志性 logo 和动态加载动画。",
        startScreen: "开始界面",
        startScreenDesc: "主菜单界面，玩家可以在这里开始他们的射箭冒险。",
        gameplayScreen: "游戏界面",
        gameplayScreenDesc: "主要游戏界面，展示射箭目标和瞄准系统。",
        successScreen: "成功界面",
        successScreenDesc: "当玩家成功击中目标时显示的胜利界面。",
        failedScreen: "失败界面",
        failedScreenDesc: "当玩家未击中目标时显示的界面，鼓励玩家再次尝试。",
        aimingSceneDesc: "瞄准场景 - 精确的射击角度计算",
        hitEffectDesc: "成功命中 - 箭精确地击中苹果"
    },
    ja: {
        // Navigation
        home: "ホーム",
        gameIntro: "ゲーム紹介",
        media: "メディア",
        guide: "ガイド",
        talk: "トーク",
        
        // Game Intro Page
        gameTitle: "AppleShooter - クラシック・シューティングゲーム",
        gameDescription: "AppleShooterは、人々の頭の上に置かれたリンゴを弓矢で正確に射抜く、チャレンジングなシューティングゲームです。プレイヤーの正確性、忍耐力、スキルが試され、一射一射が勝利か敗北かを分けます。",
        gameplay: "ゲームプレイ",
        basicControls: "基本操作",
        basicControlsDesc: "マウスで狙う：マウスを動かして矢の方向を調整",
        chargeControl: "左マウスボタンを押し続ける：チャージ、押し続けるほど矢の威力が増加",
        fireControl: "左マウスボタンを離す：矢を放つ",
        gameObjectives: "ゲームの目標",
        gameObjectivesDesc: "リンゴに正確に命中させ、人物に当てないようにする",
        levelDifficulty: "各レベルには異なる難易度と課題があります",
        highScore: "正確な射撃でハイスコアを獲得",
        gameFeatures: "ゲームの特徴",
        gameFeaturesDesc: "物理エンジン：リアルな矢の飛行軌道",
        increasingDifficulty: "難易度の上昇：徐々に増加するゲームの難易度",
        instantFeedback: "即時フィードバック：直感的な命中効果",
        gameHistory: "ゲームの歴史",
        gameHistoryDesc: "AppleShooterは、スイスの民話ウィリアム・テルの伝説からインスピレーションを得ています。",
        developmentTeam: "開発チーム",
        developmentTeamDesc: "AppleShooterは、情熱的なゲーム開発チームによって作られました。",
        developmentHistory: "開発の歴史",
        history2005: "2005年：ゲームコンセプトが誕生し、初期開発が開始",
        history2006: "2006年：最初のFlashバージョンをリリース",
        history2010: "2010年：新しいゲームメカニクスを追加した改良版をリリース",
        history2015: "2015年：HTML5バージョンをリリース、モバイルデバイスに対応",
        history2020: "2020年：メジャーアップグレード、ゲーム体験を最適化",
        coreTeam: "コアチーム",
        gameDesign: "ゲームデザイン：",
        gameDesigner: "ジョン・スミス - 10年のカジュアルゲーム開発経験を持つシニアゲームデザイナー",
        programming: "プログラミング：",
        programmer: "サラ・ジョンソン - リードプログラマー、物理エンジンの最適化を担当",
        artDesign: "アートデザイン：",
        artist: "マイケル・チェン - シニアゲームアーティスト、ビジュアルスタイルデザインを担当",
        soundDesign: "サウンドデザイン：",
        soundDesigner: "リサ・ワン - サウンドデザイナー、ゲーム音楽と効果音を制作",
        
        // Media Page
        gameMedia: "ゲームメディア",
        gameScreenshots: "ゲームスクリーンショット",
        gameScreenshotsDesc: "素晴らしいゲーム内の瞬間を見る",
        gameMusic: "ゲーム音楽",
        gameMusicDesc: "ゲームサウンドトラックを聴く",
        gameVideos: "ゲーム動画",
        gameVideosDesc: "ゲームプレイ動画を見る",
        
        // Screenshots Page
        loadingScreen: "ローディング画面",
        loadingScreenDesc: "AppleShooterの象徴的なロゴとダイナミックなローディングアニメーションが特徴のゲームのローディング画面。",
        startScreen: "スタート画面",
        startScreenDesc: "プレイヤーがアーチェリーの冒険を始めることができるメインメニュー画面。",
        gameplayScreen: "ゲームプレイ画面",
        gameplayScreenDesc: "アーチェリーターゲットと照準システムを表示するメインゲームプレイインターフェース。",
        successScreen: "成功画面",
        successScreenDesc: "プレイヤーが目標に成功した時に表示される勝利画面。",
        failedScreen: "失敗画面",
        failedScreenDesc: "プレイヤーが目標を外した時に表示される画面で、再挑戦を促します。",
        aimingSceneDesc: "照準シーン - 正確な射撃角度の計算",
        hitEffectDesc: "成功ヒット - 矢がリンゴに正確に命中"
    },
    ko: {
        // Navigation
        home: "홈",
        gameIntro: "게임 소개",
        media: "미디어",
        guide: "가이드",
        talk: "토크",
        
        // Game Intro Page
        gameTitle: "AppleShooter - 클래식 슈팅 게임",
        gameDescription: "AppleShooter는 사람들의 머리 위에 놓인 사과를 활과 화살로 정확하게 쏘아야 하는 도전적인 슈팅 게임입니다. 게임은 플레이어의 정확성, 인내심, 기술을 시험하며, 각 샷이 승리 또는 패배를 결정짓습니다.",
        gameplay: "게임플레이",
        basicControls: "기본 조작",
        basicControlsDesc: "마우스로 조준: 마우스를 움직여 화살의 방향 조정",
        chargeControl: "왼쪽 마우스 버튼 홀드: 차지, 홀드 시간에 따라 화살의 힘이 증가",
        fireControl: "왼쪽 마우스 버튼 해제: 화살 발사",
        gameObjectives: "게임 목표",
        gameObjectivesDesc: "사과를 정확하게 맞추고, 사람을 맞추지 않도록 하세요",
        levelDifficulty: "각 레벨마다 다른 난이도와 도전과제가 있습니다",
        highScore: "정확한 슈팅으로 고득점 획득",
        gameFeatures: "게임 특징",
        gameFeaturesDesc: "물리 엔진: 현실적인 화살 비행 궤적",
        increasingDifficulty: "난이도 증가: 점진적으로 증가하는 게임 난이도",
        instantFeedback: "즉각적인 피드백: 직관적인 명중 효과",
        gameHistory: "게임 역사",
        gameHistoryDesc: "AppleShooter는 스위스 민간 전설 윌리엄 텔에서 영감을 받았습니다.",
        developmentTeam: "개발 팀",
        developmentTeamDesc: "AppleShooter는 열정적인 게임 개발 팀이 만들었습니다.",
        developmentHistory: "개발 역사",
        history2005: "2005년: 게임 컨셉 탄생, 초기 개발 시작",
        history2006: "2006년: 첫 Flash 버전 출시",
        history2010: "2010년: 새로운 게임 메카닉을 추가한 개선 버전 출시",
        history2015: "2015년: HTML5 버전 출시, 모바일 기기 지원",
        history2020: "2020년: 메이저 업그레이드, 게임 경험 최적화",
        coreTeam: "핵심 팀",
        gameDesign: "게임 디자인:",
        gameDesigner: "존 스미스 - 10년의 캐주얼 게임 개발 경험을 가진 시니어 게임 디자이너",
        programming: "프로그래밍:",
        programmer: "사라 존슨 - 리드 프로그래머, 물리 엔진 최적화 담당",
        artDesign: "아트 디자인:",
        artist: "마이클 첸 - 시니어 게임 아티스트, 비주얼 스타일 디자인 담당",
        soundDesign: "사운드 디자인:",
        soundDesigner: "리사 왕 - 사운드 디자이너, 게임 음악과 효과음 제작",
        
        // Media Page
        gameMedia: "게임 미디어",
        gameScreenshots: "게임 스크린샷",
        gameScreenshotsDesc: "놀라운 게임 순간들을 보기",
        gameMusic: "게임 음악",
        gameMusicDesc: "게임 사운드트랙 듣기",
        gameVideos: "게임 비디오",
        gameVideosDesc: "게임플레이 비디오 보기",
        
        // Screenshots Page
        loadingScreen: "로딩 화면",
        loadingScreenDesc: "AppleShooter의 상징적인 로고와 다이나믹한 로딩 애니메이션이 특징인 게임의 로딩 화면.",
        startScreen: "시작 화면",
        startScreenDesc: "플레이어가 양궁 모험을 시작할 수 있는 메인 메뉴 화면.",
        gameplayScreen: "게임플레이 화면",
        gameplayScreenDesc: "양궁 타겟과 조준 시스템을 보여주는 메인 게임플레이 인터페이스.",
        successScreen: "성공 화면",
        successScreenDesc: "플레이어가 목표를 성공적으로 맞췄을 때 나타나는 승리 화면.",
        failedScreen: "실패 화면",
        failedScreenDesc: "플레이어가 목표를 놓쳤을 때 나타나는 화면으로, 다시 시도하도록 격려합니다.",
        aimingSceneDesc: "조준 장면 - 정확한 발사 각도 계산",
        hitEffectDesc: "성공적인 명중 - 화살이 사과를 정확하게 맞춤"
    },
    es: {
        // Navigation
        home: "Inicio",
        gameIntro: "Introducción",
        media: "Medios",
        guide: "Guía",
        talk: "Charla",
        
        // Game Intro Page
        gameTitle: "AppleShooter - Juego Clásico de Tiro",
        gameDescription: "AppleShooter es un desafiante juego de tiro donde los jugadores deben usar un arco y flecha para disparar con precisión a las manzanas colocadas sobre las cabezas de las personas. El juego pone a prueba la precisión, paciencia y habilidad de los jugadores, con cada disparo potencialmente trayendo victoria o derrota.",
        gameplay: "Jugabilidad",
        basicControls: "Controles Básicos",
        basicControlsDesc: "Usar el ratón para apuntar: Mover el ratón para ajustar la dirección de la flecha",
        chargeControl: "Mantener presionado el botón izquierdo del ratón: Cargar, el poder de la flecha aumenta con el tiempo",
        fireControl: "Soltar el botón izquierdo del ratón: Disparar la flecha",
        gameObjectives: "Objetivos del Juego",
        gameObjectivesDesc: "Golpear con precisión la manzana, evitar golpear a la persona",
        levelDifficulty: "Cada nivel tiene diferentes dificultades y desafíos",
        highScore: "Obtener puntuaciones altas mediante tiros precisos",
        gameFeatures: "Características del Juego",
        gameFeaturesDesc: "Motor físico: Trayectoria realista del vuelo de la flecha",
        increasingDifficulty: "Dificultad creciente: Dificultad del juego aumenta gradualmente",
        instantFeedback: "Retroalimentación instantánea: Efectos intuitivos de impacto",
        gameHistory: "Historia del Juego",
        gameHistoryDesc: "La inspiración para AppleShooter proviene de la leyenda folclórica suiza de Guillermo Tell.",
        developmentTeam: "Equipo de Desarrollo",
        developmentTeamDesc: "AppleShooter es creado por un apasionado equipo de desarrollo de juegos.",
        developmentHistory: "Historia del Desarrollo",
        history2005: "2005: Nace el concepto del juego, comienza el desarrollo inicial",
        history2006: "2006: Primera versión Flash lanzada",
        history2010: "2010: Versión mejorada lanzada con nueva mecánica de juego",
        history2015: "2015: Versión HTML5 lanzada, compatible con dispositivos móviles",
        history2020: "2020: Actualización importante, optimizando la experiencia de juego",
        coreTeam: "Equipo Principal",
        gameDesign: "Diseño del Juego:",
        gameDesigner: "John Smith - Diseñador senior de juegos con 10 años de experiencia en juegos casuales",
        programming: "Programación:",
        programmer: "Sarah Johnson - Programadora líder, enfocada en la optimización del motor físico",
        artDesign: "Diseño Artístico:",
        artist: "Michael Chen - Artista senior de juegos, responsable del diseño del estilo visual",
        soundDesign: "Diseño de Sonido:",
        soundDesigner: "Lisa Wang - Diseñadora de sonido, creando música y efectos de sonido del juego",
        
        // Media Page
        gameMedia: "Medios del Juego",
        gameScreenshots: "Capturas de Pantalla",
        gameScreenshotsDesc: "Ver momentos increíbles del juego",
        gameMusic: "Música del Juego",
        gameMusicDesc: "Escuchar la banda sonora del juego",
        gameVideos: "Videos del Juego",
        gameVideosDesc: "Ver videos del gameplay",
        
        // Screenshots Page
        loadingScreen: "Pantalla de Carga",
        loadingScreenDesc: "La pantalla de carga del juego con el icónico logo de AppleShooter y una animación dinámica de carga.",
        startScreen: "Pantalla de Inicio",
        startScreenDesc: "La pantalla del menú principal donde los jugadores pueden comenzar su aventura de tiro con arco.",
        gameplayScreen: "Pantalla de Juego",
        gameplayScreenDesc: "La interfaz principal del juego que muestra el objetivo de tiro con arco y el sistema de puntería.",
        successScreen: "Pantalla de Éxito",
        successScreenDesc: "La pantalla de victoria que aparece cuando los jugadores aciertan exitosamente en su objetivo.",
        failedScreen: "Pantalla de Fallo",
        failedScreenDesc: "La pantalla que aparece cuando los jugadores fallan su objetivo, animándolos a intentarlo de nuevo.",
        aimingSceneDesc: "Escena de Puntería - Cálculo preciso del ángulo de disparo",
        hitEffectDesc: "Impacto Exitoso - La flecha golpea con precisión la manzana"
    }
}; 